name: clean_nepali_calendar
description: Highly customizable Nepali Calendar package.
version: 1.0.0
homepage: https://github.com/lohanidamodar/clean_nepali_calendar

environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  nepali_utils: ">=2.2.0 <3.0.0"

  dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
